apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: $TARGET_NAMESPACE

images:
  - name: $AZURE_VOTE_IMAGE_REPO/azure-vote-front
    newTag: $FRONTEND_IMAGE
  - name: $AZURE_VOTE_IMAGE_REPO/azure-vote-back
    newTag: $BACKEND_IMAGE
resources:
  - manifests.yaml